/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentiRouteImport } from './routes/_authenticated/agenti'
import { Route as AuthenticatedCanaliRouteImport } from './routes/_authenticated/canali'
import { Route as AuthenticatedConversazioniRouteImport } from './routes/_authenticated/conversazioni'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedToolRouteImport } from './routes/_authenticated/tool'
import { Route as AuthenticatedWorkflowRouteImport } from './routes/_authenticated/workflow'
import { Route as AuthenticatedAgentiAgentIdRouteImport } from './routes/_authenticated/agenti_.$agentId'
import { Route as AuthenticatedCanaliChannelIdRouteImport } from './routes/_authenticated/canali_.$channelId'
import { Route as AuthenticatedToolToolIdRouteImport } from './routes/_authenticated/tool_.$toolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentiRoute = AuthenticatedAgentiRouteImport.update({
  id: '/agenti',
  path: '/agenti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCanaliRoute = AuthenticatedCanaliRouteImport.update({
  id: '/canali',
  path: '/canali',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversazioniRoute =
  AuthenticatedConversazioniRouteImport.update({
    id: '/conversazioni',
    path: '/conversazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolRoute = AuthenticatedToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowRoute = AuthenticatedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentiAgentIdRoute =
  AuthenticatedAgentiAgentIdRouteImport.update({
    id: '/agenti_/$agentId',
    path: '/agenti/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCanaliChannelIdRoute =
  AuthenticatedCanaliChannelIdRouteImport.update({
    id: '/canali_/$channelId',
    path: '/canali/$channelId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolToolIdRoute = AuthenticatedToolToolIdRouteImport.update({
  id: '/tool_/$toolId',
  path: '/tool/$toolId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenti': typeof AuthenticatedAgentiRoute
  '/canali': typeof AuthenticatedCanaliRoute
  '/conversazioni': typeof AuthenticatedConversazioniRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/log': typeof AuthenticatedLogRoute
  '/tool': typeof AuthenticatedToolRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/agenti/$agentId': typeof AuthenticatedAgentiAgentIdRoute
  '/canali/$channelId': typeof AuthenticatedCanaliChannelIdRoute
  '/tool/$toolId': typeof AuthenticatedToolToolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenti': typeof AuthenticatedAgentiRoute
  '/canali': typeof AuthenticatedCanaliRoute
  '/conversazioni': typeof AuthenticatedConversazioniRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/log': typeof AuthenticatedLogRoute
  '/tool': typeof AuthenticatedToolRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/agenti/$agentId': typeof AuthenticatedAgentiAgentIdRoute
  '/canali/$channelId': typeof AuthenticatedCanaliChannelIdRoute
  '/tool/$toolId': typeof AuthenticatedToolToolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenti': typeof AuthenticatedAgentiRoute
  '/_authenticated/canali': typeof AuthenticatedCanaliRoute
  '/_authenticated/conversazioni': typeof AuthenticatedConversazioniRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/tool': typeof AuthenticatedToolRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowRoute
  '/_authenticated/agenti_/$agentId': typeof AuthenticatedAgentiAgentIdRoute
  '/_authenticated/canali_/$channelId': typeof AuthenticatedCanaliChannelIdRoute
  '/_authenticated/tool_/$toolId': typeof AuthenticatedToolToolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenti'
    | '/canali'
    | '/conversazioni'
    | '/dashboard'
    | '/impostazioni'
    | '/log'
    | '/tool'
    | '/workflow'
    | '/agenti/$agentId'
    | '/canali/$channelId'
    | '/tool/$toolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenti'
    | '/canali'
    | '/conversazioni'
    | '/dashboard'
    | '/impostazioni'
    | '/log'
    | '/tool'
    | '/workflow'
    | '/agenti/$agentId'
    | '/canali/$channelId'
    | '/tool/$toolId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenti'
    | '/_authenticated/canali'
    | '/_authenticated/conversazioni'
    | '/_authenticated/dashboard'
    | '/_authenticated/impostazioni'
    | '/_authenticated/log'
    | '/_authenticated/tool'
    | '/_authenticated/workflow'
    | '/_authenticated/agenti_/$agentId'
    | '/_authenticated/canali_/$channelId'
    | '/_authenticated/tool_/$toolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenti': {
      id: '/_authenticated/agenti'
      path: '/agenti'
      fullPath: '/agenti'
      preLoaderRoute: typeof AuthenticatedAgentiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canali': {
      id: '/_authenticated/canali'
      path: '/canali'
      fullPath: '/canali'
      preLoaderRoute: typeof AuthenticatedCanaliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversazioni': {
      id: '/_authenticated/conversazioni'
      path: '/conversazioni'
      fullPath: '/conversazioni'
      preLoaderRoute: typeof AuthenticatedConversazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool': {
      id: '/_authenticated/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof AuthenticatedToolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenti_/$agentId': {
      id: '/_authenticated/agenti_/$agentId'
      path: '/agenti/$agentId'
      fullPath: '/agenti/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentiAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canali_/$channelId': {
      id: '/_authenticated/canali_/$channelId'
      path: '/canali/$channelId'
      fullPath: '/canali/$channelId'
      preLoaderRoute: typeof AuthenticatedCanaliChannelIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool_/$toolId': {
      id: '/_authenticated/tool_/$toolId'
      path: '/tool/$toolId'
      fullPath: '/tool/$toolId'
      preLoaderRoute: typeof AuthenticatedToolToolIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentiRoute: typeof AuthenticatedAgentiRoute
  AuthenticatedCanaliRoute: typeof AuthenticatedCanaliRoute
  AuthenticatedConversazioniRoute: typeof AuthenticatedConversazioniRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedToolRoute: typeof AuthenticatedToolRoute
  AuthenticatedWorkflowRoute: typeof AuthenticatedWorkflowRoute
  AuthenticatedAgentiAgentIdRoute: typeof AuthenticatedAgentiAgentIdRoute
  AuthenticatedCanaliChannelIdRoute: typeof AuthenticatedCanaliChannelIdRoute
  AuthenticatedToolToolIdRoute: typeof AuthenticatedToolToolIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentiRoute: AuthenticatedAgentiRoute,
  AuthenticatedCanaliRoute: AuthenticatedCanaliRoute,
  AuthenticatedConversazioniRoute: AuthenticatedConversazioniRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedToolRoute: AuthenticatedToolRoute,
  AuthenticatedWorkflowRoute: AuthenticatedWorkflowRoute,
  AuthenticatedAgentiAgentIdRoute: AuthenticatedAgentiAgentIdRoute,
  AuthenticatedCanaliChannelIdRoute: AuthenticatedCanaliChannelIdRoute,
  AuthenticatedToolToolIdRoute: AuthenticatedToolToolIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
