/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgentiRouteImport } from './routes/_authenticated/agenti'
import { Route as AuthenticatedCanaliRouteImport } from './routes/_authenticated/canali'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedLogRouteImport } from './routes/_authenticated/log'
import { Route as AuthenticatedToolRouteImport } from './routes/_authenticated/tool'
import { Route as AuthenticatedWorkflowRouteImport } from './routes/_authenticated/workflow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgentiRoute = AuthenticatedAgentiRouteImport.update({
  id: '/agenti',
  path: '/agenti',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCanaliRoute = AuthenticatedCanaliRouteImport.update({
  id: '/canali',
  path: '/canali',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogRoute = AuthenticatedLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolRoute = AuthenticatedToolRouteImport.update({
  id: '/tool',
  path: '/tool',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowRoute = AuthenticatedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenti': typeof AuthenticatedAgentiRoute
  '/canali': typeof AuthenticatedCanaliRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/log': typeof AuthenticatedLogRoute
  '/tool': typeof AuthenticatedToolRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenti': typeof AuthenticatedAgentiRoute
  '/canali': typeof AuthenticatedCanaliRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/log': typeof AuthenticatedLogRoute
  '/tool': typeof AuthenticatedToolRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenti': typeof AuthenticatedAgentiRoute
  '/_authenticated/canali': typeof AuthenticatedCanaliRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/log': typeof AuthenticatedLogRoute
  '/_authenticated/tool': typeof AuthenticatedToolRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenti'
    | '/canali'
    | '/dashboard'
    | '/impostazioni'
    | '/log'
    | '/tool'
    | '/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenti'
    | '/canali'
    | '/dashboard'
    | '/impostazioni'
    | '/log'
    | '/tool'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenti'
    | '/_authenticated/canali'
    | '/_authenticated/dashboard'
    | '/_authenticated/impostazioni'
    | '/_authenticated/log'
    | '/_authenticated/tool'
    | '/_authenticated/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenti': {
      id: '/_authenticated/agenti'
      path: '/agenti'
      fullPath: '/agenti'
      preLoaderRoute: typeof AuthenticatedAgentiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canali': {
      id: '/_authenticated/canali'
      path: '/canali'
      fullPath: '/canali'
      preLoaderRoute: typeof AuthenticatedCanaliRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log': {
      id: '/_authenticated/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof AuthenticatedLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool': {
      id: '/_authenticated/tool'
      path: '/tool'
      fullPath: '/tool'
      preLoaderRoute: typeof AuthenticatedToolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentiRoute: typeof AuthenticatedAgentiRoute
  AuthenticatedCanaliRoute: typeof AuthenticatedCanaliRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedLogRoute: typeof AuthenticatedLogRoute
  AuthenticatedToolRoute: typeof AuthenticatedToolRoute
  AuthenticatedWorkflowRoute: typeof AuthenticatedWorkflowRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentiRoute: AuthenticatedAgentiRoute,
  AuthenticatedCanaliRoute: AuthenticatedCanaliRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedLogRoute: AuthenticatedLogRoute,
  AuthenticatedToolRoute: AuthenticatedToolRoute,
  AuthenticatedWorkflowRoute: AuthenticatedWorkflowRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
