-- This migration was generated as a duplicate of
-- 20260907120000_channel_runtime.sql. Keeping it as a recorded no-op preserves
-- migration history while allowing clean database installations to complete.
